#!/bin/sh

### BEGIN INIT INFO
# Provides:          mongod
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the MongoDB database server
# Description:       Starts the MongoDB database server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/mongod
DAEMON_OPTS="-f /etc/mongodb/mongod.conf"
NAME="mongod"
DESC="MongoDB database server"
USER="mongodb"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

function d_start {
  echo -n "Starting $DESC: "
  start-stop-daemon --start --background --quiet \
    --make-pidfile --pidfile /var/run/$NAME.pid \
  	--chuid $USER \
  	--exec $DAEMON -- $DAEMON_OPTS || true
  echo "$NAME."

}

function d_stop {
  echo -n "Stopping $DESC: "
  start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
  	--exec $DAEMON || true
  echo "$NAME."

}

case "$1" in
  start)
    d_start
	;;
  stop)
    d_stop
	;;
  restart|force-reload)
	d_stop
	sleep 1
	d_start
	;;
  status)
	status_of_proc -p /var/run/$NAME.pid "$DAEMON" mongod && exit 0 || exit $?
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
